"""Create tables

Revision ID: 4a0276646bf9
Revises: 
Create Date: 2026-03-20 14:36:36.908427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0276646bf9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('blood_type', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('last_visit', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("blood_type IS NULL OR blood_type IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')", name='ck_patients_blood_type_valid'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_patients_status_active_inactive'),
    sa.CheckConstraint('char_length(btrim(first_name)) > 0', name='ck_patients_first_name_not_blank'),
    sa.CheckConstraint('char_length(btrim(last_name)) > 0', name='ck_patients_last_name_not_blank'),
    sa.CheckConstraint('dob <= CURRENT_DATE', name='ck_patients_dob_not_future'),
    sa.CheckConstraint('last_visit IS NULL OR last_visit <= CURRENT_DATE', name='ck_patients_last_visit_not_future'),
    sa.CheckConstraint('middle_name IS NULL OR char_length(btrim(middle_name)) > 0', name='ck_patients_middle_name_not_blank'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patients_first_name_lower', 'patients', [sa.literal_column('lower(first_name)')], unique=False)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index('ix_patients_last_name_lower', 'patients', [sa.literal_column('lower(last_name)')], unique=False)
    op.create_index('ix_patients_middle_name_lower', 'patients', [sa.literal_column('lower(middle_name)')], unique=False)
    op.create_index('ix_patients_status', 'patients', ['status'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('unit_number', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table('allergies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('allergy_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'allergy_name', name='uq_patient_allergy')
    )
    op.create_index(op.f('ix_allergies_id'), 'allergies', ['id'], unique=False)
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('condition_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'condition_name', name='uq_patient_condition')
    )
    op.create_index(op.f('ix_conditions_id'), 'conditions', ['id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('patientnotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('char_length(btrim(text)) > 0', name='ck_patientnotes_text_not_blank'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patientnotes_id'), 'patientnotes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patientnotes_id'), table_name='patientnotes')
    op.drop_table('patientnotes')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_conditions_id'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_allergies_id'), table_name='allergies')
    op.drop_table('allergies')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index('ix_patients_status', table_name='patients')
    op.drop_index('ix_patients_middle_name_lower', table_name='patients')
    op.drop_index('ix_patients_last_name_lower', table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index('ix_patients_first_name_lower', table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
